### ISSUE TITLE
[Task] Umi x ChatGPT（1）

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#10835]
@xyuanbuilds

## Task

先做 Umi x ChatGPT 的第一部分自然语言命令行。期望时间是下周五（2023.03.31）晚 12 点前有阶段性产出，注意不要大 PR，拆小 PR 分阶段提。

- [x] 完善 Command 的 Prompt 内容，控制在 3800 TOKEN 以内，功能覆盖命令行、配置（基于 umi config 命令）、环境变量
- [x] 添加常用语句的测试用例，直接调 OpenAI 做测试
- [x] 处理 openai timeout 报错，明确提示是 timeout 类的错误（现在只给了网络错误，同时 timeout 感觉有点频繁）

```bash
$ umi? start dev server with port 8888
PORT=8888 umi dev

$ umi? start dev server without mock
MOCK=none umi dev

$ umi? build without compress
COMPRESS=none umi dev

$ umi? enable mfsu
umi config set mfsu {}

$ umi? disable mfsu
umi config set mfsu false

$ umi? enable typescript
umi g tsconfig

$ umi? use terser as minifier
umi config set jsMinifier terser

# 这个先不用，umi config 还不支持复杂操作
$ umi? external react and react-dom
```

### 如何跑起来？

启动 dev。

```bash
$ pnpm run copilot:dev
```

Bash 里加个 alias（可选）。

```bash
alias "umi?"=/path/to/copilot/bin/umi-copilot.js
```

Bash 里加 OPENAI_API_KEY 环境变量。

```bash
export OPENAI_API_KEY=xxx
```

然后找个空项目。

```bash
$ umi g page index
$ umi? start dev server with port 8888
```

如果你的命令行掉不通 openai 的 server？那可能需要先做下命令行翻墙。

参考：  
[https://umijs.org/docs/api/commands](https://umijs.org/docs/api/commands)  
[https://umijs.org/docs/guides/env-variables](https://umijs.org/docs/guides/env-variables)  
[https://umijs.org/docs/api/config](https://umijs.org/docs/api/config)

**Comment by xyuanbuilds** [comment]
#10853 

- 目前命令行代理的方式无法获取请求结果，适配该代理方式
- 处理 openai timeout 报错，明确提示是 timeout 类的错误，并推荐传递 proxyUrl 用代理服务器访问

**Comment by xyuanbuilds** [comment]
#10853
已尝试 doc md -> 文档知识块 -> embedding，再对比与提问相关性提取有效内容作为上下文的 prompt 组合方式，效果不佳
后续通过详实 umi 文档，可能有所改善该实现的最终效果；或不要求必须返回具体命令行，而是仅返回建议。

暂实现定制 prompt：
1. 先 提问 需要使用的命令，如:dev 或 config
2. 再传递该命令行相关定制 prompt 作为 message，提问具体命令行；
3. 最后仅返回可执行命令行 或 提示未匹配
