### ISSUE TITLE
Prepare umi@2.2

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#1231]
* [x] 修复 babel-plugin-macros 被 babel-loader 缓存后改动不生效的问题，#1252
* [x] 支持 svg as component，#1263
* [x] 添加 react-router 的 Prompt 到 umi 的接口里，并完善例子，#1267
* [x] 完善 Plug'n'Play 支持，遗留两个问题，1) url-loader 2) jest 的 resolver，#1273
* [ ] 添加更多例子到 codesandbox，并在文档里体现，然后提 issue 鼓励 fork 一份还原问题场景
* [x] 修复没有 umi.css 时，chunks 里定义的 css 没有生成到 html 里的问题
* [x] chunks 支持被插入在 head 里，#1258
* [x] `umi g page` 在配置式路由时不退出，#1224
* [x] 修复 `umi g` 会生成 `.umi-production` 的问题，#1302
* [x] 检查 svg 文件在有测试用例时会不会有问题，[参考](https://github.com/facebook/create-react-app/blob/419a4ecda1e7b7c2f566e51c8c7bf3939dd62728/packages/react-scripts/config/jest/fileTransform.js)，#1303
* [x] 解决 travis ci 未开启的问题
* [x] 文档
* [x] 发布日志

**Comment by sorrycc** [comment]
明天发布。
