### ISSUE TITLE
UmiJS SSR TODO

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#2645]
## Background

#2543，可以根据这个例子 [umi-example-ssr-with-egg](https://github.com/umijs/umi-example-ssr-with-egg) 体验下 Umi SSR

## Proposal

- [ ] P0 文档完善 https://github.com/umijs/umi/issues/2937 #2963.
- [ ] P2 Layout getInitialProps 支持 https://github.com/umijs/umi/issues/2850
- [x] ~~P0 `@alipay/bigfish/react` alias 方式既不能 external，也不能 全量打进。https://github.com/liady/webpack-node-externals/issues/66~~ 不做 external，全量打入。服务端代码大小不影响。  https://github.com/umijs/umi/pull/2906
- [x] ~~P0 findRoute active，可以包括 *.html（/home == /home.html）~~ https://github.com/umijs/plugins/pull/7
- [x] ~~P1 dev 时禁用 babel runtime 插件（待复现）~~
- [x] ~~P1 dev 时 output 目录除了有 `umi.server.js` 外，还有大量的 `hot-update` 文件，需要优化删掉。 #2681~~
- [x]  ~~P1 dev 时 CSS Modules client 与 server 策略不一致~~
- [x] ~~P1 需要开启 manifest，才能运行~~ #2802
- [x] ~~P1 国际化 locale 报错 https://github.com/umijs/umi/pull/2786~~
- [x] ~~P1 `Page.getInitialProps` 的参数问题，https://github.com/umijs/umi/pull/2738#issuecomment-507917609~~
- [x] ~~P1 结合 dva example。https://github.com/umijs/umi-example-ssr-with-egg/blob/master/app/web/pages/home/index.jsx~~
- [x] ~~P1 [umijs/umi-request](https://github.com/umijs/umi-request) 同构请求能力，客户端/服务端请求接口共用。~~  https://github.com/umijs/umi-request/pull/65
- [x] ~~P1 基于 antd 封装的上层组件库 less 报：`SyntaxError: Invalid or unexpected token` （father）有关 https://github.com/umijs/father/issues/64~~
- [x] ~~P2: 全局变量和内存问题，删除 windows 变量~~
- [ ] P3: benchmarks 渲染对比，性能优化
- [ ] P3: 进度条及报错提示优化。[error-code-map](https://github.com/umijs/error-code-map)
- [ ] P3 提供 `umi/serve` ，降低服务端使用门槛，里面包含主要服务端框架的中间件。（需要经过实际场景检验，umi ssr 服务端最佳实践） https://github.com/umijs/umi-ssr-middlewares
* [ ] P3: 服务端支持 stream 方式，这样可以进一步提升页面性能，让 CSS 下载时间提前
* [x] P4: serverless + ssr 方案整理 ( https://github.com/umijs/umi-example-ssr/pull/10 )，  顺便提供一个 now 的 builder

@sorrycc 看看还有哪些需要补充下？

**Comment by sorrycc** [comment]
还有这里的，https://github.com/umijs/umi/pull/2543#issuecomment-500368805

**Comment by sorrycc** [comment]
* [ ] getInitialState 的参数问题，https://github.com/umijs/umi/pull/2738#issuecomment-507917609

**Comment by RunningCoderLee** [comment]
P1 umijs/umi-request 同构请求能力，客户端 / 服务端请求接口共用。

这个有具体的迭代计划吗？

**Comment by ycjcl868** [comment]
@RunningCoderLee  beta 已经支持了，欢迎使用。

https://github.com/umijs/umi-example-ssr/commit/46e1086eae5cf740f6cc2dbbda6e3e0b478b9517
https://github.com/umijs/umi-example-ssr-with-egg/commit/b74cfe5ac031a4d0f30eec0612d2d5ba3d31b9b3
