### ISSUE TITLE
[UMI UI] 问题收集

### ISSUE THREAD

**Issue by afc163** [umijs/umi#4479]
- [ ] 命令行区域多了几个滚动条。#3690
- [ ] 命令行弹出层应该占位，目前是浮层，导致上面的容器一部分内容被挡住，滚动不到底下。#3690
- [ ] read package.json failed #3709
- [ ] 在 Firefox 下，在项目列表页点击进入项目时，页面会闪动并出现错误的红色 banner。#3450
- [ ] 部分配置无法识别 object 对象。#3450
- [ ] 资产列表分页体验问题，建议改成一屏滚动，如果内容确实太多，可以滚动底部加载更多这样。#3689
  1. 直接向下滚动的浏览体验比较好，分页要一直点鼠标。建议改成一页内向下滚动自动加载。
  2. 目前分页 pageSize 太小，垂直空间比较浪费，尤其是完整模式下。
- [ ] #4456

**Comment by freya0608** [comment]
在ant design pro 中如何修改 umi ui 启动的port？感谢！

**Comment by deaver1248** [comment]
#include  <iostream>


Using namespace;



Int main;

Cout<yes thank you ill try it I also want to try anaconda>endl;

**Comment by deaver1248** [comment]
#include <iostream>

using namespacedavid;

{
cout <<that's sad cause I wanted to learn and your right>>endl;
Cout << money is an issue right now << endl;
Cout << why do you think I want iTorrent so bad << endl;
Cout <<I don't sellanything, we just like watching movies>>endl
Cout <<I mean damn, I don't mind paying when I got it<<endl;
Cout <<And I do sometimes, bad time of the year for<<
What I do>>endl;
Return 0;
}

**Comment by sorrycc** [comment]
umi ui 已不推荐使用。
