### ISSUE TITLE
umi roadmap

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#57]
1.0

* [x] PWA
* [x] Improve router, #26 
* [x] website
* [x] Comb configuration items

1.x

* [ ] Improve lighthouse score
* [ ] Plugin system
* [ ] umi-plugin-dva

**Comment by sorrycc** [comment]
Use milestone for it.
